### ISSUE TITLE
Translate PT-BR

### ISSUE THREAD

**Issue by NandoKstroNet** [GoBootcamp/book#18]
Hi everyone! Exist any translating to portuguese Brazil? I'm desiring get started!

**Comment by gerep** [comment]
@NandoKstroNet I can help you with the translation and I agree with @mhartl, that's definitely the best option.

**Comment by mattetti** [comment]
closing this issue but looking forward to your PR @NandoKstroNet & @gerep

**Comment by gerep** [comment]
Hey @mattetti I have started it today ;)

@NandoKstroNet have you started it too? I'm afraid we both work on the same thing =)
