### ISSUE TITLE
2.7 Code snippet -> Named return params

### ISSUE THREAD

**Issue by scopeviable** [GoBootcamp/book#59]
`func location(name, city string) (name, continent string)
`
should be 

`func location(name, city string) (region, continent string)
`

Running the current cod in the playground will return:

`prog.go:5: duplicate argument name
`

However, the linked playground code is correct.

**Comment by shan3k** [comment]
I'm wondering if I'm imagining / misunderstanding here. If we check the snippet on the live piece, we see "name".  On my branch I'm seeing region (unmodified)

**Comment by sebouh00** [comment]
Lines 4 and 6 are also missing `region`.

**Comment by scopeviable** [comment]
Looks like this is covered in commit/bbc12dc748867ce1c59e499a41ced639d9697289
